# DStat Testbed

In [35]:
import tensorflow as tf
import tensorflow_io as tfio
import re
import glob
import pandas as pd
import seaborn as sns
pd.set_option('display.max_rows', 200)
plotting_context = "paper"
plotting_palette = "deep"
font_scale = 1.3
sns.set(font_scale=font_scale, context=plotting_context, palette=plotting_palette)
sns.set(rc={"figure.dpi":300, 'savefig.dpi':300})
 
filepath = '/home/asa/Downloads/datasets/cv-corpus-5.1-singleword/en/clips/common_voice_en_22184457.mp3'


In [24]:
def read_and_decode_flac_1(path):
    io_tensor = tfio.IOTensor.graph(tf.int16).from_audio(path)
    audio_tensor = io_tensor.to_tensor()
    audio_tensor = tf.squeeze(audio_tensor)
    return audio_tensor

def read_file_2(path):
    return tf.io.read_file(path)

def decode_flac_2(data):
    samples = tfio.audio.decode_flac(data, dtype=tf.int32)
    audio_tensor = tf.cast(samples * (2**(16-1)-1), tf.int16)
    audio_tensor = tf.squeeze(audio_tensor)
    return audio_tensor

def read_and_decode_flac_3(filepath):
    audio = tfio.audio.AudioIOTensor(filepath)
    return audio

In [25]:
_read_flac(filepath)

<tf.Tensor: shape=(96768,), dtype=float32, numpy=
array([ 0.0000000e+00, -1.8869565e-16, -1.1745947e-16, ...,
       -8.6656637e-06, -1.2476181e-07,  7.7370823e-06], dtype=float32)>

In [30]:
binary = read_file_2(filepath)

In [27]:
t = read_and_decode_flac_3(filepath)
t

<AudioIOTensor: shape=[96768     1], dtype=<dtype: 'float32'>, rate=48000>

In [28]:
t.to_tensor()

<tf.Tensor: shape=(96768, 1), dtype=float32, numpy=
array([[ 0.0000000e+00],
       [-1.8869565e-16],
       [-1.1745947e-16],
       ...,
       [-8.6656637e-06],
       [-1.2476181e-07],
       [ 7.7370823e-06]], dtype=float32)>

In [41]:
raw = tf.io.read_file(filepath)
decoded = tfio.audio.decode_flac(raw, dtype=tf.int32)

InvalidArgumentError: unable to read metadata [Op:IO>AudioDecodeFlac]

In [33]:
tfio.audio.decode_flac(binary)

AssertionError: dtype (tf.uint8/tf.int16/tf.int32) must be provided